<!-- Shopee-Style Tracking Modal -->
<div id="trackingModal" style="display:none;position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.5);z-index:1000;padding:20px;overflow-y:auto;">
    <div style="background:#FFFFFF;border-radius:12px;max-width:90%;width:90%;max-height:90vh;margin:20px auto;box-shadow:0 20px 60px rgba(0,0,0,0.15);animation:slideUp 0.3s ease-out;display:flex;flex-direction:column;">
        <!-- Header -->
        <div style="padding:24px;border-bottom:1px solid #E5E5E5;display:flex;align-items:center;justify-content:space-between;background:#FFFFFF;">
            <div>
                <h2 style="font-size:18px;font-weight:700;color:#000000;margin:0;">Appointment Status Tracking</h2>
                <p style="font-size:12px;color:#999999;margin:6px 0 0 0;">Track your appointment progress</p>
            </div>
            <button onclick="closeTrackingModal()" style="background:none;border:none;cursor:pointer;font-size:28px;color:#999999;padding:0;width:32px;height:32px;display:flex;align-items:center;justify-content:center;transition:color 0.2s;" onmouseover="this.style.color='#000000'" onmouseout="this.style.color='#999999'">×</button>
        </div>

        <!-- Appointment Info -->
        <div id="appointmentInfo" style="padding:24px;border-bottom:1px solid #E5E5E5;background:#FFFFFF;">
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:16px;">
                <div>
                    <p style="font-size:11px;font-weight:600;color:#999999;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:6px;">Client</p>
                    <p style="font-size:14px;font-weight:600;color:#000000;margin:0;">—</p>
                </div>
                <div>
                    <p style="font-size:11px;font-weight:600;color:#999999;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:6px;">Service</p>
                    <p style="font-size:14px;font-weight:600;color:#000000;margin:0;">—</p>
                </div>
            </div>
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;">
                <div>
                    <p style="font-size:11px;font-weight:600;color:#999999;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:6px;">Date</p>
                    <p style="font-size:14px;font-weight:600;color:#000000;margin:0;">—</p>
                </div>
                <div>
                    <p style="font-size:11px;font-weight:600;color:#999999;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:6px;">Time</p>
                    <p style="font-size:14px;font-weight:600;color:#000000;margin:0;">—</p>
                </div>
            </div>
        </div>

        <!-- Progress Timeline (Shopee-style horizontal) -->
        <div style="padding:40px 24px;border-bottom:1px solid #E5E5E5;background:#FFFFFF;overflow-x:auto;">
            <div id="progressTimeline" style="position:relative;display:flex;align-items:center;justify-content:space-between;gap:8px;min-width:min-content;">
                <!-- Generated by JavaScript -->
            </div>
        </div>

        <!-- Status Details -->
        <div style="padding:32px;background:#FFFFFF;flex:1;overflow-y:auto;">
            <p style="font-size:12px;font-weight:600;color:#000000;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:24px;">Status Timeline</p>
            <div id="trackingTimeline" style="max-height:100%;">
                <!-- Will be populated by JavaScript -->
            </div>
        </div>

        <!-- Footer -->
        <div style="padding:24px;border-top:1px solid #E5E5E5;text-align:right;background:#F8F9FA;flex-shrink:0;">
            <button onclick="closeTrackingModal()" style="background:#000000;border:none;color:#FFFFFF;padding:12px 32px;border-radius:6px;cursor:pointer;font-weight:600;font-size:14px;transition:all 0.2s;" onmouseover="this.style.opacity='0.8'" onmouseout="this.style.opacity='1'">Close</button>
        </div>
    </div>
</div>

<script>
const STATUS_SEQUENCE = ['scheduled', 'confirmed', 'completed', 'cancelled', 'no_show'];
const STATUS_LABELS = {
    'scheduled': 'Order Placed',
    'confirmed': 'Confirmed',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'no_show': 'No Show'
};

const STATUS_ICONS = {
    'scheduled': '📋',
    'confirmed': '✓',
    'completed': '✓',
    'cancelled': '✕',
    'no_show': '–'
};

function openTrackingModal(appointmentId) {
    fetch(`/api/appointments/${appointmentId}/tracking`)
        .then(response => response.json())
        .then(data => {
            // Populate appointment info
            const appointmentInfo = document.getElementById('appointmentInfo');
            const dateTime = data.appointment.date_time.split(' at ');
            appointmentInfo.innerHTML = `
                <div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:16px;">
                    <div>
                        <p style="font-size:11px;font-weight:600;color:#999999;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:6px;">Client</p>
                        <p style="font-size:14px;font-weight:600;color:#000000;margin:0;">${data.appointment.client_name}</p>
                    </div>
                    <div>
                        <p style="font-size:11px;font-weight:600;color:#999999;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:6px;">Service</p>
                        <p style="font-size:14px;font-weight:600;color:#000000;margin:0;">${data.appointment.service_type}</p>
                    </div>
                </div>
                <div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;">
                    <div>
                        <p style="font-size:11px;font-weight:600;color:#999999;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:6px;">Date</p>
                        <p style="font-size:14px;font-weight:600;color:#000000;margin:0;">${dateTime[0]}</p>
                    </div>
                    <div>
                        <p style="font-size:11px;font-weight:600;color:#999999;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:6px;">Time</p>
                        <p style="font-size:14px;font-weight:600;color:#000000;margin:0;">${dateTime[1] || '—'}</p>
                    </div>
                </div>
            `;

            // Generate progress timeline
            generateProgressTimeline(data.appointment.status, data.tracking);

            // Populate history timeline
            const timeline = document.getElementById('trackingTimeline');
            timeline.innerHTML = data.tracking.map((item, index) => `
                <div style="display:flex;gap:12px;margin-bottom:${index === data.tracking.length - 1 ? '0' : '16px'};padding-bottom:${index === data.tracking.length - 1 ? '0' : '16px'};border-bottom:${index === data.tracking.length - 1 ? 'none' : '1px solid #E5E5E5'}">
                    <div style="display:flex;flex-direction:column;align-items:center;min-width:24px;">
                        <div style="width:8px;height:8px;background:#000000;border-radius:50%;position:relative;z-index:2;"></div>
                    </div>
                    <div style="flex:1;">
                        <p style="font-size:13px;font-weight:600;color:#000000;margin-bottom:4px;">${item.status_change}</p>
                        <p style="font-size:12px;color:#999999;margin-bottom:4px;">By ${item.changed_by}</p>
                        ${item.service_completed_by ? `<p style="font-size:12px;color:#999999;margin-bottom:4px;">Service by ${item.service_completed_by}</p>` : ''}
                        <p style="font-size:12px;color:#999999;">${item.timestamp}</p>
                        ${item.notes ? `<p style="font-size:12px;color:#666666;margin-top:8px;font-style:italic;">&quot;${item.notes}&quot;</p>` : ''}
                    </div>
                </div>
            `).join('');

            document.getElementById('trackingModal').style.display = 'flex';
            document.getElementById('trackingModal').style.alignItems = 'flex-start';
            document.getElementById('trackingModal').style.justifyContent = 'center';
        })
        .catch(error => console.error('Error fetching tracking data:', error));
}

function generateProgressTimeline(currentStatus, tracking) {
    const timeline = document.getElementById('progressTimeline');

    // Define all possible paths
    const paths = {
        completed: ['scheduled', 'confirmed', 'completed'],
        confirmed: ['scheduled', 'confirmed'],
        cancelled: ['scheduled', 'cancelled'],
        no_show: ['scheduled', 'no_show'],
        scheduled: ['scheduled']
    };

    // Get the path for current status
    const path = paths[currentStatus] || paths.scheduled;

    // Calculate progress percentage
    const progressPercent = (path.indexOf(currentStatus) + 1) / path.length * 100;

    // Create progress bar HTML
    const progressHTML = `
        <div style="width: 100%; position: relative;">
            <!-- Background track -->
            <div style="
                position: relative;
                height: 8px;
                background: #E5E5E5;
                border-radius: 10px;
                margin-bottom: 30px;
                overflow: hidden;
            ">
                <!-- Progress fill -->
                <div style="
                    height: 100%;
                    background: linear-gradient(90deg, #000000, #2D2D2D);
                    border-radius: 10px;
                    width: ${progressPercent}%;
                    transition: width 0.5s ease-out;
                "></div>
            </div>

            <!-- Status checkpoints -->
            <div style="display: flex; justify-content: space-between; position: relative; top: -25px;">
                ${path.map((status, index) => {
                    const isCompleted = path.indexOf(currentStatus) >= index;
                    const statusLabels = {
                        'scheduled': 'Scheduled',
                        'confirmed': 'Confirmed',
                        'completed': 'Completed',
                        'cancelled': 'Cancelled',
                        'no_show': 'No Show'
                    };
                    const statusIcons = {
                        'scheduled': '📋',
                        'confirmed': '✓',
                        'completed': '✓',
                        'cancelled': '✕',
                        'no_show': '–'
                    };
                    const statusColors = {
                        'scheduled': '#666666',
                        'confirmed': '#000000',
                        'completed': '#00AA00',
                        'cancelled': '#CC0000',
                        'no_show': '#FF6600'
                    };

                    return `
                        <div style="display: flex; flex-direction: column; align-items: center; flex: 1;">
                            <div style="
                                width: 40px;
                                height: 40px;
                                border-radius: 50%;
                                background: ${isCompleted ? statusColors[status] : '#FFFFFF'};
                                border: 3px solid ${statusColors[status]};
                                display: flex;
                                align-items: center;
                                justify-content: center;
                                font-size: 18px;
                                font-weight: 700;
                                color: ${isCompleted ? '#FFFFFF' : '#CCCCCC'};
                                margin-bottom: 12px;
                                box-shadow: ${isCompleted ? '0 2px 8px rgba(0,0,0,0.15)' : 'none'};
                            ">
                                ${statusIcons[status]}
                            </div>
                            <p style="
                                font-size: 12px;
                                font-weight: 600;
                                color: ${isCompleted ? statusColors[status] : '#CCCCCC'};
                                text-align: center;
                                width: 100%;
                                margin: 0;
                            ">
                                ${statusLabels[status]}
                            </p>
                        </div>
                    `;
                }).join('')}
            </div>
        </div>

        <!-- Progress percentage display -->
        <div style="text-align: center; margin-top: 40px; font-size: 14px; font-weight: 600; color: #666666;">
            Progress: <span style="color: #000000; font-size: 16px;">${Math.round(progressPercent)}%</span>
        </div>
    `;

    timeline.innerHTML = progressHTML;
}

function closeTrackingModal() {
    document.getElementById('trackingModal').style.display = 'none';
}

document.getElementById('trackingModal')?.addEventListener('click', function(e) {
    if (e.target === this) closeTrackingModal();
});
</script>

<style>
@keyframes slideUp {
    from {
        transform: translateY(20px);
        opacity: 0;
    }
    to {
        transform: translateY(0);
        opacity: 1;
    }
}
</style>
